/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cookieassignment;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {

    Scanner input = new Scanner(System.in);
    OrderMaster myOrder = new OrderMaster();

    String userInput = "";
    Boolean keepGoing = true;

    do {
        System.out.println("Do you want to buy some cookies? (y/n)");
        System.out.println("For a list of your current cookies, insert (i).");
        System.out.println("To remove an cookie from the list, insert (r).");
        userInput = input.nextLine();
        userInput = userInput.trim().toLowerCase();

        if (userInput.equals("y")) {
            String orderVariety = "";
            int orderQuantity = 0;

            System.out.println("What variety of cookie would you like?");
            orderVariety = input.nextLine();
            System.out.println("How many boxes would you like?");
            orderQuantity = Integer.parseInt(input.nextLine());


            Order addedOrder = new Order(orderVariety, orderQuantity);
            myOrder.addOrder(addedOrder);

        } else if(userInput.equals("i")) {
            System.out.println("This is your current order: ");
            myOrder.showAllCookies();
            System.out.println("Number of boxes: " + myOrder.getTotalBoxes());
        } else if(userInput.equals("r")) {
            String orderVariety = "";
            System.out.println("What variety of cookie would you like to remove?");
            orderVariety = input.nextLine();
            myOrder.removeVariety(orderVariety);
        } else if(userInput.equals("n")) {
            keepGoing = false;
        }

    } while(keepGoing);

    System.out.println("This is all the cookies you have purchased: ");
    myOrder.showAllCookies();
    System.out.println("Number of boxes: " + myOrder.getTotalBoxes());


    input.close();
    }
}

